// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Referendum.core.Entities;

namespace Referendum.core.Migrations
{
    [DbContext(typeof(ReferendumContext))]
    partial class ReferendumContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Referendum.core.Entities.CitizenDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Opaque");

                    b.Property<int?>("ReferendumId");

                    b.Property<string>("Ssn");

                    b.Property<string>("Time");

                    b.HasKey("Id");

                    b.ToTable("CitizenDb");
                });

            modelBuilder.Entity("Referendum.core.Entities.CommunitiesDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommunityCode");

                    b.Property<string>("CommunityName");

                    b.HasKey("Id");

                    b.ToTable("CommunitiesDb");
                });

            modelBuilder.Entity("Referendum.core.Entities.ReferendumDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CommunityId");

                    b.Property<int?>("ConnectionCount");

                    b.Property<DateTime?>("EndDate");

                    b.Property<bool?>("IsActive");

                    b.Property<string>("Question");

                    b.Property<DateTime?>("StartDate");

                    b.HasKey("Id");

                    b.ToTable("ReferendumDb");
                });
#pragma warning restore 612, 618
        }
    }
}
